export const ErrorCodes = {
  AUTH: {
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    REFRESH_TOKEN_REQUIRED: 'REFRESH_TOKEN_REQUIRED',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    AUTHENTICATION_TOKEN_REQUIRED: 'AUTHENTICATION_TOKEN_REQUIRED',
    AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED'
  },
  USER: {
    NOT_FOUND: 'USER_NOT_FOUND',
    CANNOT_DELETE_SELF: 'CANNOT_DELETE_SELF',
    INVALID_ROLE: 'INVALID_ROLE',
    CANNOT_CHANGE_OWN_ROLE: 'CANNOT_CHANGE_OWN_ROLE'
  },
  VALIDATION: {
    REQUIRED_FIELD: 'REQUIRED_FIELD',
    INVALID_FORMAT: 'INVALID_FORMAT',
    INVALID_REQUEST: 'INVALID_REQUEST'
  }
} as const;
