name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        with:
          host: 10.0.0.14
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'cd /opt/banedonv && ./deploy.sh dev'
      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: 10.0.0.2
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 'cd /opt/banedonv && ./deploy.sh prod'
